apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-auth
  labels:
    app: fc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-auth
  template:
    metadata:
      labels:
        app: fc-auth
    spec:
      containers:
        - name: fc-auth
          image: kyun4000/fcauth:0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD